language: node_js

node_js:
  - "node"

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    sudo: required
install:
# Install required packages
  - sudo apt-get install -y inkscape
  - sudo -H pip install rst2html5
  - sudo -H pip install rst2pdf
  - sudo -H pip install svglib
# Install fonts
  - wget https://www.paratype.com/uni/public/PTSans.zip
  - wget https://www.paratype.com/uni/public/PTSerif.zip
  - wget https://www.paratype.com/uni/public/PTMono.zip
  - unzip PTSans.zip -d PTSans
  - unzip PTSerif.zip -d PTSerif
  - unzip PTMono.zip -d PTMono
  - ls
# Rename fonts
  - mv PTSans/PTN57F.ttf PTSans/PT_Sans-Narrow-Web-Regular.ttf
  - mv PTSans/PTN77F.ttf PTSans/PT_Sans-Narrow-Web-Bold.ttf
  - mv PTSans/PTS55F.ttf PTSans/PT_Sans-Web-Regular.ttf
  - mv PTSans/PTS56F.ttf PTSans/PT_Sans-Web-Italic.ttf
  - mv PTSans/PTS75F.ttf PTSans/PT_Sans-Web-Bold.ttf
  - mv PTSans/PTS76F.ttf PTSans/PT_Sans-Web-BoldItalic.ttf
  - mv PTSerif/PTF55F.ttf PTSerif/PT_Serif-Web-Regular.ttf
  - mv PTSerif/PTF56F.ttf PTSerif/PT_Serif-Web-Italic.ttf
  - mv PTSerif/PTF75F.ttf PTSerif/PT_Serif-Web-Bold.ttf
  - mv PTSerif/PTF76F.ttf PTSerif/PT_Serif-Web-BoldItalic.ttf
  - mv PTMono/PTM55F.ttf PTMono/PTM55FT.ttf
# Copy fonts
  - sudo cp PTSans/*.ttf /usr/share/fonts/
  - sudo cp PTSerif/*.ttf /usr/share/fonts/
  - sudo cp PTMono/*.ttf /usr/share/fonts/
  - fc-cache -f -v
# Clean-up
  - rm PTSans.zip PTMono.zip PTSerif.zip
  - rm -r PTMono PTSans PTSerif

script:
  - git checkout $TRAVIS_BRANCH
  - ls
  - ls /usr/share/fonts
  - make html
  - make pdf
  - ls
  - ls pdf
  - git diff
  - git status
# Push back if changes detected
  - |
    echo Check for git changes...
    echo ${TRAVIS_COMMIT_MESSAGE}
    echo ${TRAVIS_REPO_SLUG}
    if git diff-index --no-ext-diff --name-only --exit-code HEAD ./camadapter ./index.html ./css ./head; then
        echo No changes detected
    else
        echo Detected changes
        echo This commit message is
        echo ${TRAVIS_COMMIT_MESSAGE}
        if [[ ${TRAVIS_COMMIT_MESSAGE} != *"norepush"* ]]; then
          echo Pushing changes back...
          git config --global user.email "travis@travis-ci.org"
          git config --global user.name "Travis CI"
          git commit -a -m "Travis automatic commit (__norepush__)"
          git remote add origin-pages https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG} > /dev/null 2>&1
          git push --quiet origin-pages master
          echo Pushing finished
        else
          echo Looks like it was a travis automatic commit. Don\'t push back.
        fi
    fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: pdf/*
  skip_cleanup: true 
  on:
    tags: true
    
