language: node_js

node_js:
  - "node"

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    sudo: required
install:
# Install required packages
  - sudo pip install rst2html5
  - sudo pip install rst2pdf
  - sudo pip install svglib
  - npm install js-yaml
# Install fonts
  - wget https://www.paratype.com/uni/public/PTSans.zip
  - wget https://www.paratype.com/uni/public/PTSerif.zip
  - wget https://www.paratype.com/uni/public/PTMono.zip
  - unzip PTSans.zip -d PTSans
  - unzip PTSerif.zip -d PTSerif
  - unzip PTMono.zip -d PTMono
  - ls
# Rename fonts
  - mv PTSans/PTN57F.ttf PTSans/PT_Sans-Narrow-Web-Regular.ttf
  - mv PTSans/PTN77F.ttf PTSans/PT_Sans-Narrow-Web-Bold.ttf
  - mv PTSans/PTS55F.ttf PTSans/PT_Sans-Web-Regular.ttf
  - mv PTSans/PTS56F.ttf PTSans/PT_Sans-Web-Italic.ttf
  - mv PTSans/PTS75F.ttf PTSans/PT_Sans-Web-Bold.ttf
  - mv PTSans/PTS76F.ttf PTSans/PT_Sans-Web-BoldItalic.ttf
  - mv PTSerif/PTF55F.ttf PTSerif/PT_Serif-Web-Regular.ttf
  - mv PTSerif/PTF56F.ttf PTSerif/PT_Serif-Web-Italic.ttf
  - mv PTSerif/PTF75F.ttf PTSerif/PT_Serif-Web-Bold.ttf
  - mv PTSerif/PTF76F.ttf PTSerif/PT_Serif-Web-BoldItalic.ttf
  - mv PTMono/PTM55F.ttf PTMono/PTM55FT.ttf
# Copy fonts
  - sudo cp PTSans/*.ttf /usr/share/fonts/
  - sudo cp PTSerif/*.ttf /usr/share/fonts/
  - sudo cp PTMono/*.ttf /usr/share/fonts/
  - fc-cache -f -v
# Clean-up
  - rm PTSans.zip PTMono.zip PTSerif.zip
  - rm -r PTMono PTSans PTSerif

script:
  - ls
  - ls /usr/share/fonts
  - make html
  - make pdf
  - ls
  - ls pdf
  - git diff
  - git status
# Build finished
  - |
    if [ -n {TRAVIS_TAG+1} ]; then
      VER=`echo $TRAVIS_TAG | sed -r "s/v?(.*)/\1/"`
      echo Version is $VER
      export VER
      zip -j airmast-docs-${VER}.zip ./pdf/*
    fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - ${TRAVIS_BUILD_DIR}/airmast-docs-${VER}.zip
  skip_cleanup: true 
  on:
    tags: true
    
